title: tanish-kr's learning log
description: Learning output log
lang: ja_JP
plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at
last-modified-at:
    date-format: '%Y-%m-%d %H:%M:%S'
google_analytics: UA-63042509-4
sass:
  style: compact
kramdown:
  parse_block_html: true
